version: '3.7'
services:
  hojicha-frontend:
    container_name: hojicha-frontend
    build:
      context: ../packages/frontend
    ports:
      - '80:8001'
    networks:
      - 'hojicha-net'

networks:
  hojicha-net:

volumes:
  db-data:
